### ISSUE TITLE
crash on unknown model

### ISSUE THREAD

**Issue by ghobson2013** [lord-server/panorama#37]
Hi there, 

First of all thanks for this great tool...

While loading the media if the model is unknown currently i get a SIGSEV memory violation
in game.go lResolveNode function
A simple nill check avoids the problem and allows the LoadGame to complete.
see PR request.

Also i had a question around loading media from 2 different sources, minetest_game is one but mods is a different folder, 
is there a way to pass more than 1 media path ?

Regards,
Gary

**Comment by weqqr** [comment]
Thanks for the report!

Game loading (and the mapper in general) is largely incomplete since the only game we tested was our own :)

Fetching media from different paths never crossed my mind, but should be fairly straightforward to implement. I created issue
#39 for that.
